### ISSUE TITLE
[influxdb2] chart failing on arm64/k8s 1.22/containerd

### ISSUE THREAD

**Issue by sdeoras** [influxdata/helm-charts#374] opened 2021-10-31 12:51 UTC
I am running into following errors when trying to install chart version 2.0.1 on an arm64 based k8s cluster running kubernetes version 1.22 using `containerd` runtime. 
It is not clear to me if this is a bug or it can be easily fixed via config in values.yaml. Appreciate any help, thanks!

pod going in crash-loop:
```└─ $ ▶ kubectl --namespace=influxdb-system get pods,pvc,svc
NAME                       READY   STATUS             RESTARTS      AGE
pod/influxdb-influxdb2-0   0/1     CrashLoopBackOff   9 (62s ago)   16m

NAME                                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/influxdb-influxdb2   Bound    pvc-7e86b31c-1a82-47a0-a8eb-a715d16153ad   50Gi       RWO            nfs            16m

NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/influxdb-influxdb2   ClusterIP   10.106.193.154   <none>        80/TCP    16m
```

pod logs show more info:
```
└─ $ ▶ kubectl --namespace=influxdb-system logs -f pod/influxdb-influxdb2-0
time="2021-10-31T12:33:07Z" level=info msg="reset OCSP cache file. /root/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=info msg="reading OCSP Response cache file. /root/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=error msg="failed to open. Ignored. open /root/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:07Z" level=info msg="reset OCSP cache file. /root/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=info msg="reading OCSP Response cache file. /root/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=error msg="failed to open. Ignored. open /root/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:07Z" level=info msg="reset OCSP cache file. /root/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=info msg="reading OCSP Response cache file. /root/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=error msg="failed to open. Ignored. open /root/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:07Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:07Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:08Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:08Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:08Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:08Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
time="2021-10-31T12:33:08Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:08Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
2021-10-31T12:33:08.986434585Z	info	booting influxd server in the background	{"system": "docker"}
time="2021-10-31T12:33:09Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:09Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
time="2021-10-31T12:33:09Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
2021-10-31T12:33:09.996253648Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "0"}
2021-10-31T12:33:11.100625029Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "1"}
2021-10-31T12:33:12.203005923Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "2"}
2021-10-31T12:33:13.299640762Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "3"}
2021-10-31T12:33:14.399486531Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "4"}
2021-10-31T12:33:15.499165915Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "5"}
2021-10-31T12:33:16.600216183Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "6"}
2021-10-31T12:33:17.705536901Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "7"}
2021-10-31T12:33:18.806221324Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "8"}
2021-10-31T12:33:19.906718195Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "9"}
2021-10-31T12:33:21.006719389Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "10"}
2021-10-31T12:33:22.109153285Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "11"}
2021-10-31T12:33:23.211695420Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "12"}
2021-10-31T12:33:24.319861667Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "13"}
2021-10-31T12:33:25.425502493Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "14"}
2021-10-31T12:33:26.528812931Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "15"}
2021-10-31T12:33:27.632784858Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "16"}
2021-10-31T12:33:28.738590682Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "17"}
2021-10-31T12:33:29.841553478Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "18"}
2021-10-31T12:33:30.947580391Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "19"}
2021-10-31T12:33:32.050402227Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "20"}
2021-10-31T12:33:33.153733110Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "21"}
2021-10-31T12:33:34.257137456Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "22"}
2021-10-31T12:33:35.356555885Z	info	pinging influxd...	{"system": "docker", "ping_attempt": "23"}
2021-10-31T12:33:36.485367781Z	warn	cleaning bolt and engine files to prevent conflicts on retry	{"system": "docker", "bolt_path": "/var/lib/influxdbv2/influxd.bolt", "engine_path": "/var/lib/influxdbv2"}
rm: cannot remove '/var/lib/influxdbv2': Permission denied
```

**Comment by sdeoras** [comment] 2021-10-31 13:43
#324 fixes this issue

**Comment by saiharshitachava** [comment] 2021-11-02 14:07
I have the same issue 
Do we have a fix 
adding startup probe dint fix this

**Comment by sdeoras** [comment] 2021-11-02 15:05
@saiharshitachava it fixed the bootup problem on my setup, however, script trying to remove a path it does not own is still an issue, so i left the bug open.

**Comment by abhi1693** [comment] 2021-11-05 13:54
I had submitted a fix that I'm using from a forked repo in my cluster but Influx does not want to implement as PSP are deprecated

https://github.com/influxdata/helm-charts/pull/372

**Comment by samip5** [comment] 2021-11-12 10:17
Actually duplicate of #350

**Comment by alespour** [comment] 2021-11-24 15:47
Closing as #324 fixed the first issue and the second is duplicate of #350.

**Closed by alespour** 2021-11-24 15:47 UTC
